replicaCount: 1

image:
  repository: n8nio/n8n
  tag: "2.11.0-arm64"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5678
  nodePort: 31678

persistence:
  enabled: true
  storageClass: longhorn
  size: 2Gi
  accessMode: ReadWriteOnce

resources: {}

deploymentStrategy: Recreate

env:
  timezone: UTC
  protocol: http
  encryptionKeySecretName: n8n-encryption-key
  encryptionKeySecretKey: encryptionKey
  secureCookie: false
  webhookUrl: ""
