replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: "v1.13.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 6333
  grpcPort: 6334

persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi
  accessMode: ReadWriteOnce

resources: {}

deploymentStrategy: Recreate
